version: "3"
services:
  ember_app:
    build:
      dockerfile: Dockerfile
      context: "./"
    ports:
      - "4200:4200"

  api_app:
    build:
      context: ./pastoral-visit-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pastoral-visit-api:/rails
    environment:
      DATABASE_URL: postgres://username:password@db:5432/pastoral_visit_api_development
    depends_on:
      - db

  db:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "pastoral_visit_api_development"
