name: Ember.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test Ember.js app
        run: |
          docker build -t ember-app .
          docker run ember-app npm test
