name: Ember.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Initialize and Update Submodules
        run: |
          git submodule update --init --recursive

      - name: Run docker
        run: |
          docker-compose up -d
          docker-compose ps

      # - name: Install Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: "3.2.2"

      # - name: Bundle Install for Submodule
      #   working-directory: pastoral-visit-api
      #   run: |
      #     gem install bundler
      #     bundle install

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
